name: Web automated testing with Selenium, Pytest and GitHub Actions
run-name: Pipeline Selenium and Pytest
on:
  pull_request:
  push: { branches: [master] }
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5

      - name: Setup Chrome
      - uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true

      - name: Setup firefox
      - uses: browser-actions/setup-firefox@v1
        with:
          install-geckodriver: true

      - name: Install packages in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test pytest
        run: pytest --browser=firefox --html logs/report.html src/

      - name: Run test allure
        run: pytest --browser=firefox --alluredir allure-results src/

      - name: Upload Test Artifacts Pytest html
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: /home/runner/work/selenium-python-pytest/selenium-python-pytest/logs/

      - name: Upload Test Artifacts Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: /home/runner/work/selenium-python-pytest/selenium-python-pytest/allure-results/