name: Web automated testing with Selenium, Pytest and GitHub Actions
run-name: Pipeline Selenium and Pytest
on:
  pull_request:
  push: { branches: [master] }
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true

      - name: Setup firefox
        uses: browser-actions/setup-firefox@v1

      - name: Install packages in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test chrome
        run: pytest --browser=chrome --alluredir allure-results src/

      - name: Upload Test Artifacts Chrome
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-chrome
          path: /home/runner/work/selenium-python-pytest/selenium-python-pytest/allure-results/

      - name: Run test firefox
        run: pytest --browser=firefox --alluredir allure-results src/

      - name: Upload Test Artifacts Firefox
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-firefox
          path: /home/runner/work/selenium-python-pytest/selenium-python-pytest/allure-results/