name: Web automated testing with Selenium, Pytest and GitHub Actions
run-name: Pipeline Selenium and Pytest
on:
  pull_request:
  push: { branches: [master] }
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Chrome
        uses: nanasess/setup-chromedriver@v2.2.2

      - name: Install packages in requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test
        run: pytest --html logs/report.html src/

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: /home/runner/work/robot-github-actions/robot-github-actions/logs/